on:
  issues:
    types: [labeled]

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Move to Backlog
        uses: bishalrai96/Project_Card_Automation@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          label: "ğŸ“‹ Backlog"
          column: "ğŸ“‹ Backlog"
          remove-label: "ğŸ”– Ready,ğŸ— In progress,ğŸ‘€ In review,âœ… Done"
      - name: Move to Ready
        uses: bishalrai96/Project_Card_Automation@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          label: "ğŸ”– Ready"
          column: "ğŸ”– Ready"
          remove-label: "ğŸ“‹ Backlog,ğŸ— In progress,ğŸ‘€ In review,âœ… Done"
      - name: Move to In Progress
        uses: bishalrai96/Project_Card_Automation@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          label: "ğŸ— In progress"
          column: "ğŸ— In progress"
          remove-label: "ğŸ“‹ Backlog,ğŸ”– Ready,ğŸ‘€ In review,âœ… Done"
      - name: Move to In review
        uses: bishalrai96/Project_Card_Automation@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          label: "ğŸ‘€ In review"
          column: "ğŸ‘€ In review"
          remove-label: " ğŸ“‹ Backlog,ğŸ”– Ready,ğŸ— In progress,âœ… Done"
      - name: Move to Done
        uses: bishalrai96/Project_Card_Automation@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          label: "âœ… Done"
          column: "âœ… Done"
          remove-label: " ğŸ“‹ Backlog,ğŸ”– Ready,ğŸ— In progress,ğŸ‘€ In review"

